### ISSUE TITLE
 Config not saving

### ISSUE THREAD

**Issue by localghost8000** [statamic-rad-pack/mailchimp#100]
Statamic  4.10.0. 

The Mailchimp configuration emits a successful save notification, however, the changes don't persist, so it appears saving is actually failing. I've published the configuration, etc, but no luck getting this to work so far. For additional context, I'm using the Peak starter kit.

**Comment by edalzell** [comment]
Can you please split these into 2 separate issues please?

I'll take a look at the saving as soon as I can. In the meantime you can fill in the config file manually, as a workaround.

**Comment by ryanmitchell** [comment]
@edalzell @localghost8000 I was able to recreate the saving issue, so I've raised an issue here https://github.com/Stillat/proteus/issues/23 if you want to follow along.

**Comment by edalzell** [comment]
@localghost8000 can you please run a `composer update` and see if the saving is fixed now, as Proteus was recently updated.

**Comment by localghost8000** [comment]
@edalzell I can confirm its now saving!
