### ISSUE TITLE
Z-Index on the Config page (Statamic 4.9-4.10.0)

### ISSUE THREAD

**Issue by localghost8000** [statamic-rad-pack/mailchimp#101]
There seems to be a stacking issue with several of the fields on the config. Pictured below.

<img width="434" alt="Screenshot 2023-07-05 at 8 51 50 PM" src="https://github.com/silentzco/statamic-mailchimp/assets/2650558/f4543aa9-a71d-4113-9b72-63957b899850">

**Comment by robdekort** [comment]
This is probably an issue in Statamic Core cuz of the v4 changes regarding select fields.

**Comment by ryanmitchell** [comment]
Yep it is. I've raised an issue here if you want to follow along:
https://github.com/statamic/cms/issues/8468

**Comment by jasonvarga** [comment]
This needs to be fixed in this addon since the field is using the `v-select` component directly, and not a built-in fieldtype.

**Comment by edalzell** [comment]
Fixed in https://github.com/statamic-rad-pack/mailchimp/pull/109
