### ISSUE TITLE
Add back permissions feature

### ISSUE THREAD

**Issue by edalzell** [statamic-rad-pack/mailchimp#105]
It got removed from Spatie's Newsletter package, needs to be added back.

Likely do this in concert with #104

**Comment by ryanmitchell** [comment]
Can you flesh this one out a bit more - I'm happy to work on it but I'm not familiar enough with the project to know what this means.

**Comment by edalzell** [comment]
Sure, hop on Discord if/when you'd like to tackle, but essentially the code here: https://github.com/statamic-rad-pack/mailchimp/blob/925e06ac8cecfb26953665d42de1c90bd10f15fc/src/Subscriber.php#L131 needs to be updated to use the mailchimp API instead of the Spatie package, because the package removed that feature.

My plans was to copy the code from the v4 version of the package, and update appropriately.
