### ISSUE TITLE
Vite manifest not found

### ISSUE THREAD

**Issue by geertjanknapen1** [statamic-rad-pack/mailchimp#108]
After installing the addon. Setting API key. And publishing config, all of the pages in my controle panel (with the exception of Dashboard) throw a `Vite manifest not found` exception.

It suggests running `npm run dev` which does nothing. 
We are using webpack.

Full exception:

```
Vite manifest not found at: /usr/share/nginx/html/public/vendor/mailchimp/build/manifest.json (View: /usr/share/nginx/html/vendor/statamic/cms/resources/views/partials/scripts.blade.php) (View: /usr/share/nginx/html/vendor/statamic/cms/resources/views/partials/scripts.blade.php) (View: /usr/share/nginx/html/vendor/statamic/cms/resources/views/partials/scripts.blade.php)
```

**Comment by geertjanknapen1** [comment]
@ryanmitchell 

Environment
Application Name: website
Laravel Version: 10.13.5
PHP Version: 8.2.6
Composer Version: 2.5.7
Environment: local
Debug Mode: ENABLED
URL: website.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
edalzell/forma: 2.1
spatie/statamic-responsive-images: 4.0.3
statamic-rad-pack/mailchimp: 4.1.0
statamic/eloquent-driver: 2.0.0
withcandour/aardvark-seo: 3.0.0

**Comment by ryanmitchell** [comment]
You deleted out the Statamic section - can you add it please.

**Comment by geertjanknapen1** [comment]
@ryanmitchell Sorry, somehow didn't copy over

Environment
Application Name: website
Laravel Version: 10.13.5
PHP Version: 8.2.6
Composer Version: 2.5.7
Environment: local
Debug Mode: ENABLED
URL: website.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: stack / daily
Mail: smtp
Queue: database
Session: file

Statamic
Addons: 6
Antlers: runtime
Stache Watcher: Disabled
Static Caching: Disabled
Version: 4.6.0 PRO

Statamic Addons
aryehraber/statamic-impersonator: 2.5.0
edalzell/forma: 2.1
spatie/statamic-responsive-images: 4.0.3
statamic-rad-pack/mailchimp: 4.1.0
statamic/eloquent-driver: 2.0.0
withcandour/aardvark-seo: 3.0.0

**Comment by ryanmitchell** [comment]
Interesting, all seems in order.
I can see the `public/vendor/mailchimp/build/manifest.json` file on my install too. 
Does that folder have any files for you?

**Comment by ryanmitchell** [comment]
Sounds like something has failed during the install.
Did you give `pixelfear/composer-dist-plugin` permission to execute when asked?

**Comment by geertjanknapen1** [comment]
Yes I did. `pixelfear/composer-dist-plugin": true,`

I guess I could try reinstalling?

**Comment by ryanmitchell** [comment]
Yeah I dont see why its failed.
Another option would be to manually download and place the dist folder (https://github.com/statamic-rad-pack/mailchimp/releases/download/v4.1.0/dist.tar.gz)

**Comment by geertjanknapen1** [comment]
Downloading `dist` directory and putting it in there doesn't make a difference. Will be re-installing in a minute, I'll let you know if it works.

Would it matter that I am running on a Docker setup and in WSL2? I don't suppose so, but you never know ofcourse.

**Comment by geertjanknapen1** [comment]
So it works now. I reinstalled twice in order to get the `dist` dir. Perhaps something regarding my connection being unstable or something. I have no clue
