### ISSUE TITLE
Should we remove all default values?

### ISSUE THREAD

**Issue by ryanmitchell** [statamic-rad-pack/mailchimp#111]
The default form we supply with the add-on doesn't actually work as a form when you hit save. The pre-configured values can cause issues. See video from @robdekort 

https://github.com/statamic-rad-pack/mailchimp/assets/51899/ca366ee9-9d72-4c27-9aeb-4fba0496ad38

Should we look to remove all default values from the config and just add them as comments?

**Comment by edalzell** [comment]
Ya agreed, let's improve the docs and remove the defaults.
