### ISSUE TITLE
I can't get the marketing permissions field

### ISSUE THREAD

**Issue by danielreales7** [statamic-rad-pack/mailchimp#122]
### Description

When the form is submitted and send data to MailChimp in this point: `$this->setMarketingPermissions();` the `$field` value is always null.

I don't know if I'm following the steps wrong but it's not entirely clear to me.

### Steps to reproduce

I attach my configuration:

```php
<?php

return [

    'api_key' => env('MAILCHIMP_API_KEY'),

    /*
     * Set to `true` to add new user registrations to a Mailchimp audience.
     */
    'add_new_users' => false,

    'users' => [
        /*
        * A Mailchimp Audience ID.
        *
        * @see https://mailchimp.com/help/find-audience-id/.
        */
        'audience_id' => 'XXXXX',

        /*
        * Set to `true` to require consent before subscribing someone
        * Default: `true`
        */
        'check_consent' => true,

        /*
        * Field name used to check for consent.
        * Default: 'consent'
        */
        'consent_field' => 'consent',

        /*
        * Disable Double Opt In. Not typically a best practice.
        * Default: `false`
        *
        * @see https://mailchimp.com/help/single-opt-in-vs-double-opt-in/
        */

        'disable_opt_in' => false,

        /*
        * Field name used to collect ids of group "interests".
        * Default: 'interests'
        *
        * @see https://mailchimp.com/help/how-to-use-groups-to-add-or-update-subscriber-preferences/
        */
        'interests_field' => 'interests',

        /*
        * Field name used to indicate marketing permissions.
        * Default: `gdpr`
        */
        'marketing_permissions_field' => 'consent',

        /*
        * Fields used to store marketing permission ids.
        * Run `php please mailchimp:permissions <form-handle>` to get the ids.
        */
        'marketing_permissions_field_ids' => [
            // [
            //     'field_name' => '',
            //     'id' => '',
            // ],
        ],

        /*
        * Store information about your contacts with marge fields.
        *
        * @see https://mailchimp.com/help/manage-audience-signup-form-fields/
        */
        'merge_fields' => [
            // [
            //     /*
            //     * The Mailchimp tag
            //     */
            //     'tag'=> null,

            //     /*
            //     * Blueprint field name to use for the merge field
            //     */
            //     'field_name' => null,
            // ],
        ],

        /*
        * Field that contains the primary email address
        * Default: 'email'
        */
        'primary_email_field' => 'email',

        /*
        * Mailchimp Tag to assign to the contact.
        * NOTE: `tag_field` takes precedence over `tag`
        *
        * @see https://mailchimp.com/help/getting-started-tags/
        */
        'tag' => null,

        /*
        * Field to indicate which Mailchimp Tag to use
        *
        * @see https://mailchimp.com/help/getting-started-tags/
        */
        'tag_field' => 'email',
        'id' => 'HTLci5UL',
    ],

    /*
     * The form submissions to add to your Mailchimp Audiences
     */
    'forms' => [
        [
            'id' => 'xxxx',
            'form' => 'newsletter',
            'primary_email_field' => 'email',
            'disable_opt_in' => false,
            'check_consent' => true,
            'consent_field' => 'consent',
            'marketing_permissions_field' => 'consent',
            'audience_id' => 'xxxxx',
            'marketing_permissions_field_ids' => [
                [
                    'id' => 'xxxxx',
                    'field_name' => 'email',
                ],
            ],
        ],
    ],

    /*
     * The listName to use when no listName has been specified in a method.
     */
    'defaultListName' => 'subscribers',
];

```

Y only have a simple input text for email and check for consent.

This is the error:

[2024-07-23 13:35:28] local.ERROR: StatamicRadPack\Mailchimp\NewsletterDriver::setMarketingPermission(): Argument #2 ($permission) must be of type string, null given, called in /Users/daniel/Desktop/Proyectos/dragonfly-institute/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 355 {"userId":"f9451e6b-7eb0-427d-abf0-7e6b51519944","exception":"[object] (TypeError(code: 0): StatamicRadPack\\Mailchimp\\NewsletterDriver::setMarketingPermission(): Argument #2 ($permission) must be of type string, null given, called in /Users/daniel/Desktop/Proyectos/dragonfly-institute/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 355 at /Users/daniel/Desktop/Proyectos/dragonfly-institute/vendor/statamic-rad-pack/mailchimp/src/NewsletterDriver.php:395)
[stacktrace]
#0 /Users/daniel/Desktop/Proyectos/dragonfly-institute/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(355): StatamicRadPack\\Mailchimp\\NewsletterDriver->setMarketingPermission('test@test.com', NULL, true, 'newsletter')

### Environment

Environment
Application Name: Dragonfly Institute
Laravel Version: 10.48.16
PHP Version: 8.2.21
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: dragonfly-institute.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 7
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.17.0 PRO

Statamic Addons
edalzell/forma: 3.0.1
spatie/statamic-responsive-images: 5.0.0
statamic-rad-pack/mailchimp: 5.0.1
studio1902/statamic-peak-browser-appearance: 3.5.0
studio1902/statamic-peak-commands: 8.4.0
studio1902/statamic-peak-seo: 8.15.3
studio1902/statamic-peak-tools: 6.3.0

**Comment by ryanmitchell** [comment]
Do you have a field called `consent` in your form and is it being output on the front end?

**Comment by danielreales7** [comment]
> Do you have a field called `consent` in your form and is it being output on the front end?

![image](https://github.com/user-attachments/assets/42ff58cf-443e-40f4-b1bb-8b50d4697138)

I have only two fields, email input and consent.

**Comment by edalzell** [comment]
Sorry I've been on vacation this week, I'll take a look at this next week.

**Comment by ryanmitchell** [comment]
We got this sorted on discord.

**Comment by danielreales7** [comment]
> We got this sorted on discord.

Yes! It was the answer:

The issue is you have marketing_permissions_field set to consent - thats intended for the marketing permissions functionality which is different from the boolean consent [https://mailchimp.com/help/collect-consent-with-gdpr-forms/](https://mailchimp.com/help/collect-consent-with-gdpr-forms/)
just leave that field blank and it should work for you
