### ISSUE TITLE
CP translation file is not working properly

### ISSUE THREAD

**Issue by danielreales7** [statamic-rad-pack/mailchimp#134]
### Description

I have a Statamic project with the following:

APP_LOCALE=es
APP_FALLBACK_LOCALE=es
APP_FAKER_LOCALE=es_ES

And the control panel translation appears in English. However, if I change APP_LOCALE=en to Spanish. I have tried to comment out the boot() of the service provider and if I leave APP_LOCALE=es I get it in Spanish but if I change it to English I get it in Spanish too. It's quite strange. But after installing the package and having multisite in my project this started happening.

### Steps to reproduce

1. Configure multisite. (I don't know exactly if it's because of multisite but I only have two languages ​​configured in the project)
2. Install package.
3. Go to CP

### Environment

Environment
Application Name: Statamic
Laravel Version: 11.27.1
PHP Version: 8.2.23
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: vivenda_pitiusa.test
Maintenance Mode: OFF
Timezone: UTC
Locale: es

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 9
Sites: 2 (Español, English)
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.30.0 PRO

Statamic Addons
jacksleight/statamic-bard-texstyle: 3.3.0
ndx/statamic-bard-color-picker: 2.0.0
spatie/statamic-responsive-images: 5.0.1
statamic-rad-pack/mailchimp: 5.2.1
studio1902/statamic-peak-browser-appearance: 3.5.0
studio1902/statamic-peak-commands: 2.7.0
studio1902/statamic-peak-seo: 7.5.0
studio1902/statamic-peak-tools: 3.4.3

**Comment by edalzell** [comment]
From discord: 
![CleanShot 2024-10-08 at 17 37 12@2x](https://github.com/user-attachments/assets/1ba4cd69-767c-4b77-8fa4-57e945ed45c0)

**Comment by ryanmitchell** [comment]
If you move that line inside the app->booted() closure beneath it does it work as expected?

**Comment by edalzell** [comment]
Ya I was thinking it should be in a bootAddon method. 

We could also clean this up and use the autoloading stuff.
